## Travis CI Integration

language: c

env:
  - EnableNuGetPackageRestore=true

 before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel > /dev/null
  - mozroots --import --sync

script:
 - xbuild src/ThaiNumberSpelling.sln
 - nunit-console lib/Dinobenz.ThaiNumberSpelling.Test.dll
