## Travis CI Integration
language: csharp
solution: src/ThaiNumberSpelling.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore src/ThaiNumberSpelling.sln

script:
  - xbuild src/ThaiNumberSpelling.sln
  - nunit-console lib/Dinobenz.ThaiNumberSpelling.Test.dll