## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild src/ThaiNumberSpelling.sln
  - nunit-console lib/Dinobenz.ThaiNumberSpelling.Test.dll
